### PR TITLE
Responding to callout for charter members

### PR DESCRIPTION
**Pull request by jabhay**
We did a callout for charter members. These changes
address the responses we received.

### CODE REVIEW

**Review by lvdbrink — COMMENTED** [review]
Need to clarify if more than 1 person from a single member org may be charter member. If so add
G. Wiersma | Geonovum 

Also add
Paul Cripps | Defence Science & Technology Laboratories (Dstl)
Simon Cox | CSIRO

**Comment by jabhay** [comment]
> Need to clarify if more than 1 person from a single member org may be charter member. If so add
> G. Wiersma | Geonovum
> 
> Also add
> Paul Cripps | Defence Science & Technology Laboratories (Dstl)
> Simon Cox | CSIRO

These changes have already been made :)

**Comment by lvdbrink** [comment]
Add 
Rachel Heaven| British Geological Survey

**Comment by jabhay** [comment]
> Add
> Rachel Heaven| British Geological Survey

Done

**Pull request merged**
