### PR TITLE
Update clause_3.adoc

### PR DESCRIPTION
**Pull request by FransKnibbe**
Add a section about GeoSPARQL support in current IT systems

### CODE REVIEW

**Comment by chris-little** [comment]
@FransKnibbe "Requirement 8: Integration of Geometry with aspatial data" Is 'aspatial' a typo for 'spatial' or do you mean 'non-spatial' which is a better word less likely to be misread.

"Requirement 15: Comform with GML" typo for 'conform'

"Stardog is a platform for knowledge graphs and it supports GeoPSPARQL." typo for GeoSPARQL

**Comment by FransKnibbe** [comment]
Chris, thank you for your vigilance. I've just fixed all three typos, although not all of them were mine :-). I see requirement 8 comes from the GeoSPARQL document, where it is said to be intended for associating geometries with features. So I'm fairly sure 'spatial' was intended in this case. It does makes me wonder if, under an open world assumption, non-spatial data can become spatial once geometry is associated...

**Review by jabhay — APPROVED** [review]
Looks great!

**Comment by lieberjosh** [comment]
@FransKnibbe That was the original goal of the GeoRSS OWL geometry properties -- to convert any class, such as an Atom entry, into "isalsoA" spatial feature.

**Pull request merged**
